// =============================================================================
// The user-facing identifier for a Service.
//
// A Service's primary key is a database UUID. It is an INTERNAL identifier and
// it does not belong in anything a user can see: it appears in operator logs,
// in support transcripts and in admin screens, so once it is in a page, a URL
// or a screenshot it correlates the two contexts for anyone who ever sees both.
// It is also long enough to invite being pasted around as though it were a
// public handle.
//
// The bot has always shown a SHORT id instead — the first 8 hex characters of
// the uuid, which is what appears in its callback data and its Persian screens.
// The Mini App shows the same thing, so a user reading «شناسه: 1a2b3c4d» in the
// bot and in the browser is reading one identifier, not two.
//
// The format lives here rather than in either app because both must agree
// exactly: the bot renders it, the API resolves it, and a private copy in
// either would be free to drift. Resolution itself is NOT here — it needs a
// database and an owner, and each app scopes its own query.
// =============================================================================

/** Characters of the uuid taken. 8 hex chars = 32 bits. */
export const SERVICE_SHORT_ID_LENGTH = 8;

/**
 * The public identifier for a service.
 *
 * A prefix rather than a hash so an operator holding the internal uuid can
 * still recognise the service a user is talking about without a lookup table,
 * and so the value is stable for the row's whole life with nothing to store.
 */
export function serviceShortId(service: { id: string }): string {
  return service.id.slice(0, SERVICE_SHORT_ID_LENGTH);
}

/**
 * Exactly the shape `serviceShortId` produces — no more, no less.
 *
 * The bot accepts a looser 4–32 character prefix because its callback data is
 * generated by the bot itself and a stale button is harmless. A public HTTP
 * surface should not: accepting shorter prefixes turns the detail route into a
 * prefix-enumeration oracle over the caller's own account, and accepting longer
 * ones would let a caller supply the full uuid and keep it in circulation.
 */
export const SERVICE_PUBLIC_ID_PATTERN = /^[0-9a-f]{8}$/i;

/** True when `value` could be a public service id (format only, no lookup). */
export function isServicePublicId(value: unknown): value is string {
  return typeof value === "string" && SERVICE_PUBLIC_ID_PATTERN.test(value);
}

/**
 * The ONE canonical form of a public id, or null when it is not one.
 *
 * Hex is case-insensitive, so `AB12CD34` and `ab12cd34` name the same row —
 * and anything that treats them as different strings will eventually treat one
 * request as two. That bit us: an idempotency fingerprint built from the raw
 * transport value made a retry that changed case look like a different
 * mutation, so a user who resubmitted from a client that upper-cased the id
 * would have been told their retry conflicted.
 *
 * So there is exactly one place that decides what a public id "is", and both
 * the lookup and the fingerprint use its output. Never the raw value.
 */
export function canonicalPublicId(value: unknown, pattern: RegExp): string | null {
  return typeof value === "string" && pattern.test(value) ? value.toLowerCase() : null;
}

/** Canonical lowercase service public id, or null. */
export function canonicalServicePublicId(value: unknown): string | null {
  return canonicalPublicId(value, SERVICE_PUBLIC_ID_PATTERN);
}

// --- support tickets ---------------------------------------------------------
//
// The same reasoning, for the same reason. A SupportTicket's primary key is a
// uuid that appears in operator logs and admin screens; a ticket's public
// identifier is what the user reads in the bot and in the Mini App, and the two
// must be one value. The bot has always addressed tickets by a uuid PREFIX in
// its callback data — this names that format instead of leaving each caller to
// slice the string itself.
//
// Resolution is deliberately NOT here: it needs a database and an owner, and
// every caller must scope its own query by the authenticated user.

/** Characters of the uuid taken. 8 hex chars = 32 bits, as for services. */
export const TICKET_SHORT_ID_LENGTH = 8;

/** The public identifier for a support ticket. */
export function ticketShortId(ticket: { id: string }): string {
  return ticket.id.slice(0, TICKET_SHORT_ID_LENGTH);
}

/**
 * Exactly the shape `ticketShortId` produces.
 *
 * The bot's own callback data may carry a looser prefix because the bot
 * generated it and a stale button is harmless. An HTTP surface accepts this and
 * nothing else: a shorter prefix would turn the detail route into a
 * prefix-enumeration oracle over the caller's own tickets, and a longer one
 * would let a caller keep a full uuid in circulation.
 */
export const TICKET_PUBLIC_ID_PATTERN = /^[0-9a-f]{8}$/i;

/** True when `value` could be a public ticket id (format only, no lookup). */
export function isTicketPublicId(value: unknown): value is string {
  return typeof value === "string" && TICKET_PUBLIC_ID_PATTERN.test(value);
}

/** Canonical lowercase ticket public id, or null. Same discipline as services. */
export function canonicalTicketPublicId(value: unknown): string | null {
  return canonicalPublicId(value, TICKET_PUBLIC_ID_PATTERN);
}

// --- commerce entities (miniapp-commerce-parity, Phase 1) ---------------------
//
// The same reasoning, extended to the commerce rows the Mini App must address:
// checkouts, payments, orders, other-product orders, products, categories and
// panels. The bot already renders 8-hex uuid prefixes for all of them in its
// callback data (checkoutShortId, paymentShortId, productShortId, ...); these
// constants name the one format both transports share. Resolution stays with
// each caller — owner-scoped for owned rows, visibility-scoped for catalog
// rows — via `id: { startsWith }` + `take: 2` ambiguity detection.

/** Characters of the uuid taken — one convention for every commerce entity. */
export const COMMERCE_SHORT_ID_LENGTH = 8;

/** The public identifier for any commerce row addressed by uuid prefix. */
export function commerceShortId(row: { id: string }): string {
  return row.id.slice(0, COMMERCE_SHORT_ID_LENGTH);
}

/** Exactly the shape `commerceShortId` produces — same strictness as services. */
export const COMMERCE_PUBLIC_ID_PATTERN = /^[0-9a-f]{8}$/i;

/** Canonical lowercase commerce public id, or null. */
export function canonicalCommercePublicId(value: unknown): string | null {
  return canonicalPublicId(value, COMMERCE_PUBLIC_ID_PATTERN);
}
